const CHORDS = {
  C:{name:'C Major',shape:'x 3 2 0 1 0',fingers:[null,3,2,null,1,null],description:'A foundational open chord with a bright, clear sound.',tip:'Keep the first finger curled so the high E string stays open.',difficulty:'Beginner'},
  G:{name:'G Major',shape:'3 2 0 0 0 3',fingers:[2,1,null,null,null,3],description:'A bright open chord that appears in hundreds of songs.',tip:'Keep your wrist relaxed and let all six strings ring.',difficulty:'Beginner'},
  Em:{name:'E Minor',shape:'0 2 2 0 0 0',fingers:[null,1,2,null,null,null],description:'One of the easiest minor chords and a great first chord.',tip:'Play every string. The open E strings should ring clearly.',difficulty:'Beginner'},
  Am:{name:'A Minor',shape:'x 0 2 2 1 0',fingers:[null,null,2,3,1,null],description:'A warm minor chord with a compact three-finger shape.',tip:'Start strumming from the A string, not the low E.',difficulty:'Beginner'},
  D:{name:'D Major',shape:'x x 0 2 3 2',fingers:[null,null,null,1,3,2],description:'A compact open chord with a clear, ringing top end.',tip:'Only strum from the D string downward.',difficulty:'Beginner'},
  E:{name:'E Major',shape:'0 2 2 1 0 0',fingers:[null,2,3,1,null,null],description:'A strong major chord that is also a useful barre-chord starting point.',tip:'Keep the index finger close to the fret so the G string rings cleanly.',difficulty:'Beginner'},
  A:{name:'A Major',shape:'x 0 2 2 2 0',fingers:[null,null,1,2,3,null],description:'A classic open major shape. Three fingers share the 2nd fret.',tip:'Try lining the three fingers up neatly without muting the high E.',difficulty:'Beginner'},
  Dm:{name:'D Minor',shape:'x x 0 2 3 1',fingers:[null,null,null,2,3,1],description:'A darker variation of D major.',tip:'Keep the high E finger tucked close to the fret.',difficulty:'Beginner'},
  F:{name:'F Major',shape:'1 3 3 2 1 1',fingers:['barre',3,3,2,1,1],description:'A full first-fret barre chord. A key step toward movable shapes.',tip:'Build the barre slowly. Check each string individually before strumming.',difficulty:'Intermediate'},
  Bm:{name:'B Minor',shape:'x 2 4 4 3 2',fingers:[null,'barre',4,4,3,2],description:'A movable minor barre chord.',tip:'Roll the index finger slightly toward its side to make the barre cleaner.',difficulty:'Intermediate'},
  Em7:{name:'E Minor 7',shape:'0 2 0 0 0 0',fingers:[null,1,null,null,null,null],description:'A softer, more open version of E minor.',tip:'Let every open string ring around the fretted A string.',difficulty:'Beginner'},
  Asus2:{name:'A Suspended 2',shape:'x 0 2 2 0 0',fingers:[null,null,1,2,null,null],description:'An airy A shape with open B and high E strings.',tip:'It sounds especially good when you let the top strings ring.',difficulty:'Beginner'},
  Cadd9:{name:'C Add 9',shape:'x 3 2 0 3 3',fingers:[null,3,2,null,1,1],description:'A colourful C shape with a ringing upper voicing.',tip:'Keep the top two strings ringing and avoid the low E.',difficulty:'Beginner'},
  Dsus4:{name:'D Suspended 4',shape:'x x 0 2 3 3',fingers:[null,null,null,1,2,3],description:'A suspended D shape that naturally resolves back to D.',tip:'Move the high E finger on and off to hear the suspension resolve.',difficulty:'Beginner'},
  A7:{name:'A Dominant 7',shape:'x 0 2 0 2 0',fingers:[null,null,2,null,3,null],description:'A bluesy dominant chord with a little more tension than A major.',tip:'Let the open G, B and high E strings ring.',difficulty:'Beginner'},
  E7:{name:'E Dominant 7',shape:'0 2 0 1 0 0',fingers:[null,2,null,1,null,null],description:'A classic blues and folk chord with a strong pull toward A.',tip:'Keep the G string clear; it is what gives this chord its character.',difficulty:'Beginner'}
};

const SONGS = [
{id:'perfect',title:'Perfect',artist:'Ed Sheeran',difficulty:'Easy',vibe:'sad',chords:['G','Em','C','D'],strum:['↓','↓↑','↑↓↑'],note:'A simplified beginner arrangement. Keep the rhythm gentle and let each chord ring.'},
{id:'let-her-go',title:'Let Her Go',artist:'Passenger',difficulty:'Easy',vibe:'sad',chords:['G','D','Em','C'],strum:['↓','↓↑','↑↓↑'],note:'A simple four-chord practice arrangement for smooth changes.'},
{id:'riptide',title:'Riptide',artist:'Vance Joy',difficulty:'Easy',vibe:'warm',chords:['Am','G','C'],strum:['↓','↓↑','↑↓↑'],note:'Keep the strum light and consistent. Start slowly before adding the full pattern.'},
{id:'someone-you-loved',title:'Someone You Loved',artist:'Lewis Capaldi',difficulty:'Easy',vibe:'sad',chords:['C','G','Am','F'],strum:['↓','↓↑','↑↓↑'],note:'Use a relaxed pulse and practise the move into F slowly.'},
{id:'count-on-me',title:'Count on Me',artist:'Bruno Mars',difficulty:'Easy',vibe:'warm',chords:['C','G','Am','F'],strum:['↓','↓↑','↓↑'],note:'A friendly four-chord loop for practising steady rhythm.'},
{id:'im-yours',title:"I'm Yours",artist:'Jason Mraz',difficulty:'Easy',vibe:'warm',chords:['G','D','Em','C'],strum:['↓','↓↑','↑↓↑'],note:'Keep the groove loose and even in this simplified arrangement.'},
{id:'zombie',title:'Zombie',artist:'The Cranberries',difficulty:'Easy',vibe:'strong',chords:['Em','C','G','D'],strum:['↓','↓','↓↑','↓↑'],note:'Use stronger downbeats for a heavier feel.'},
{id:'knockin',title:"Knockin' on Heaven's Door",artist:'Bob Dylan',difficulty:'Easy',vibe:'warm',chords:['G','D','Am','C'],strum:['↓','↓↑','↑↓↑'],note:'A classic progression for practising clean changes without rushing.'},
{id:'stand-by-me',title:'Stand by Me',artist:'Ben E. King',difficulty:'Easy',vibe:'warm',chords:['G','Em','C','D'],strum:['↓','↓↑','↓↑'],note:'Keep each chord even and let the loop settle into a steady pulse.'},
{id:'hallelujah',title:'Hallelujah',artist:'Leonard Cohen',difficulty:'Easy',vibe:'sad',chords:['C','Am','F','G'],strum:['↓','↓↑','↑↓↑'],note:'Try slow picking first, then move to a gentle strum.'},
{id:'cant-help-falling',title:"Can't Help Falling in Love",artist:'Elvis Presley',difficulty:'Easy',vibe:'soft',chords:['C','G','Am','F','C','G','C'],strum:['↓','↓↑','↓↑'],note:'Let the open chords ring and avoid rushing the transitions.'},
{id:'house-rising-sun',title:'House of the Rising Sun',artist:'The Animals',difficulty:'Medium',vibe:'sad',chords:['Am','C','D','F'],strum:['P i m a','P i m a','P i m a'],note:'A fingerpicking-focused arrangement. Keep the picking hand relaxed.'},
{id:'wonderwall',title:'Wonderwall',artist:'Oasis',difficulty:'Medium',vibe:'soft',chords:['Em7','G','Dsus4','A'],strum:['↓','↓↑','↑↓↑'],note:'A simplified arrangement using the familiar suspended voicing.'},
{id:'photograph',title:'Photograph',artist:'Ed Sheeran',difficulty:'Easy',vibe:'soft',chords:['G','Em','C','D'],strum:['↓','↓↑','↑↓↑'],note:'A simple four-chord practice arrangement with a soft pulse.'},
{id:'scarborough-fair',title:'Scarborough Fair',artist:'Traditional',difficulty:'Easy',vibe:'calm',chords:['Am','G','Am','Em'],strum:['↓','↓↑','↑↓↑'],note:'A traditional tune that works well for minor-key movement.'},
{id:'amazing-grace',title:'Amazing Grace',artist:'Traditional',difficulty:'Easy',vibe:'calm',chords:['G','C','G','D'],strum:['↓','↓↑','↓↑'],note:'A simple traditional arrangement for practising clean open chords.'},
{id:'greensleeves',title:'Greensleeves',artist:'Traditional',difficulty:'Medium',vibe:'calm',chords:['Am','G','F','E'],strum:['↓','↓↑','↓↑'],note:'A useful progression for practising minor-key movement.'},
{id:'auld-lang-syne',title:'Auld Lang Syne',artist:'Traditional',difficulty:'Easy',vibe:'warm',chords:['G','D','G','C'],strum:['↓','↓↑','↓↑'],note:'Great for smooth open-chord changes.'},
{id:'saints',title:'When the Saints Go Marching In',artist:'Traditional',difficulty:'Easy',vibe:'strong',chords:['C','F','C','G'],strum:['↓','↓','↓↑'],note:'Accent the first beat of each bar for a lively feel.'},
{id:'oh-susanna',title:'Oh! Susanna',artist:'Traditional',difficulty:'Easy',vibe:'warm',chords:['G','D','G','C'],strum:['↓','↓↑','↑↓↑'],note:'A bright progression for steady beginner strumming.'}
];